/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.SortedMap;
/**
 *
 * @author leoeuler
 */
public class mainGui extends javax.swing.JFrame {

    /**
     * Creates new form mainGui
     */
    Graph g;
    public mainGui() {
        initComponents();
        g=new Graph();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modifyVerName = new javax.swing.JTextField();
        addVerName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        deleteVerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        searchVerName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        addVerX = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addVerY = new javax.swing.JTextField();
        addVerButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        modifyVerX = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        modifyVerY = new javax.swing.JTextField();
        modifyVerButton = new javax.swing.JButton();
        deleteVerButton = new javax.swing.JButton();
        searchVerButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        modifyEdgeFrom = new javax.swing.JTextField();
        addEdgeTo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        deleteEdgeFrom = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        searchEdgeFrom = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        addEdgeButton = new javax.swing.JButton();
        modifyEdgeButton = new javax.swing.JButton();
        deleteEdgeButton = new javax.swing.JButton();
        searchEdgeButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        addEdgeFrom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addEdgeWt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        modifyEdgeTo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        modifyEdgeWt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        deleteEdgeTo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        searchEdgeTo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        djikSource = new javax.swing.JTextField();
        djikDest = new javax.swing.JTextField();
        djikFindPath = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        djikPath = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        fileName = new javax.swing.JTextField();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel2.setText("Add Vertex");

        jLabel5.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel5.setText("Modify Vertex");

        modifyVerName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        addVerName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addVerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVerNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel6.setText("Delete Vertex");

        deleteVerName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel7.setText("Search Vertex");

        searchVerName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel8.setText("Name         :");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel9.setText("Name         :");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel1.setText("Name        :");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel10.setText("Name       :");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel11.setText("X :");

        addVerX.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addVerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVerXActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel12.setText("Y :");

        addVerY.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addVerY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVerYActionPerformed(evt);
            }
        });

        addVerButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addVerButton.setText("ADD");
        addVerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVerButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel13.setText("X :");

        modifyVerX.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        modifyVerX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyVerXActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel14.setText("Y :");

        modifyVerY.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        modifyVerButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        modifyVerButton.setText("MODIFY");
        modifyVerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyVerButtonActionPerformed(evt);
            }
        });

        deleteVerButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        deleteVerButton.setText("DELETE");
        deleteVerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVerButtonActionPerformed(evt);
            }
        });

        searchVerButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        searchVerButton.setText("SEARCH");
        searchVerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addVerX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyVerX, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addVerY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyVerY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addVerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyVerButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchVerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deleteVerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(modifyVerName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addVerName, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(deleteVerButton)
                            .addComponent(searchVerButton))
                        .addGap(344, 344, 344))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addVerName)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addVerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(addVerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addVerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyVerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(modifyVerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(modifyVerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyVerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteVerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(deleteVerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchVerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchVerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vertex", jPanel1);

        jLabel3.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel3.setText("Add Edge");

        jLabel17.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel17.setText("Modify Edge");

        modifyEdgeFrom.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        addEdgeTo.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addEdgeTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeToActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel18.setText("Delete Edge");

        deleteEdgeFrom.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Nimbus Mono L", 1, 24)); // NOI18N
        jLabel19.setText("Search Edge");

        searchEdgeFrom.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel20.setText("To  : ");

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel21.setText("From      :");

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel22.setText("From        :");

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel23.setText("From       :");

        addEdgeButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addEdgeButton.setText("ADD");
        addEdgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeButtonActionPerformed(evt);
            }
        });

        modifyEdgeButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        modifyEdgeButton.setText("MODIFY");
        modifyEdgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyEdgeButtonActionPerformed(evt);
            }
        });

        deleteEdgeButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        deleteEdgeButton.setText("DELETE");
        deleteEdgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEdgeButtonActionPerformed(evt);
            }
        });

        searchEdgeButton.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        searchEdgeButton.setText("SEARCH");
        searchEdgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEdgeButtonActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel24.setText("From     :");

        addEdgeFrom.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addEdgeFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeFromActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel15.setText("Wt  :");

        addEdgeWt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        addEdgeWt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdgeWtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel16.setText("To  :");

        modifyEdgeTo.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel25.setText("Wt  : ");

        modifyEdgeWt.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel26.setText("To :");

        deleteEdgeTo.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel27.setText("To :");

        searchEdgeTo.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(deleteEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(modifyEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(searchEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(addEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel21))
                                        .addGap(34, 34, 34))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(28, 28, 28)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addEdgeTo, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(modifyEdgeTo)
                                    .addComponent(deleteEdgeTo)
                                    .addComponent(searchEdgeTo))
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addEdgeWt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modifyEdgeWt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(addEdgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modifyEdgeButton))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchEdgeButton)
                                    .addComponent(deleteEdgeButton))))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEdgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(addEdgeWt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifyEdgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(modifyEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(modifyEdgeWt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEdgeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(deleteEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEdgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(searchEdgeFrom)
                    .addComponent(searchEdgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(searchEdgeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edge", jPanel2);

        jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jLabel28.setText("Source            :");

        jLabel29.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jLabel29.setText("Destination      :");

        djikSource.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        djikSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djikSourceActionPerformed(evt);
            }
        });

        djikDest.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        djikDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djikDestActionPerformed(evt);
            }
        });

        djikFindPath.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        djikFindPath.setText("Find Path");
        djikFindPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djikFindPathActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jLabel4.setText("Path                :");

        djikPath.setColumns(20);
        djikPath.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        djikPath.setRows(5);
        jScrollPane1.setViewportView(djikPath);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(djikDest, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(djikSource))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(djikFindPath, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(djikSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(djikDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(djikFindPath, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Djikstra", jPanel3);

        jLabel30.setFont(new java.awt.Font("Nimbus Mono L", 1, 22)); // NOI18N
        jLabel30.setText("Import Graph");

        jLabel31.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jLabel31.setText("File Name      :");

        fileName.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        fileName.setText("input.txt");

        importButton.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        exportButton.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        exportButton.setText("Export Graph to File");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(fileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jTabbedPane1.addTab("Files", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVerNameActionPerformed

    private void addVerXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVerXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVerXActionPerformed

    private void addVerYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVerYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVerYActionPerformed

    private void addVerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVerButtonActionPerformed
        // TODO add your handling code here:
        String name;
        int x,y;
        try 
        {
            if(addVerName.getText().isEmpty() || addVerX.getText().isEmpty() || addVerY.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            name=addVerName.getText().trim();
            x=Integer.parseInt(addVerX.getText().trim());
            y=Integer.parseInt(addVerY.getText().trim());
            
            g.addVertex(name, x, y);
            JOptionPane.showMessageDialog(null,"Vertex added successfully !! ");
            System.out.println("New points map is -");
            g.printPointsMap();
        } 
        catch (Exception e) 
        {
            if(e instanceof NumberFormatException)
                JOptionPane.showMessageDialog(null,"The coordinates must be Integers");
            else 
                JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        
    }//GEN-LAST:event_addVerButtonActionPerformed

    private void modifyVerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyVerButtonActionPerformed
        // TODO add your handling code here:
        String name;
        int x,y;
        try 
        {
            if(modifyVerName.getText().isEmpty() || modifyVerX.getText().isEmpty() || modifyVerY.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            name=modifyVerName.getText().trim();
            x=Integer.parseInt(modifyVerX.getText().trim());
            y=Integer.parseInt(modifyVerY.getText().trim());
            
            if(!g.pointsMap.containsKey(name))
                throw new ExceptionHandler("Vertex with given name does not exist !!");
            
            g.pointsMap.get(name).set(0,x);
            g.pointsMap.get(name).set(1,y);
            
            JOptionPane.showMessageDialog(null,"New vertex - "+name + " : " + "[ " + x + ", "+ y + " ]");
            
            System.out.println("New points map is -");
            g.printPointsMap();
        } 
        catch (Exception e) 
        {
            if(e instanceof NumberFormatException)
                JOptionPane.showMessageDialog(null,"The coordinates must be Integers");
            else 
                JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_modifyVerButtonActionPerformed

    private void modifyVerXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyVerXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyVerXActionPerformed

    private void deleteVerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVerButtonActionPerformed
        // TODO add your handling code here:
        String name;
        try 
        {
            if(deleteVerName.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            name=deleteVerName.getText().trim();
        
            if(!g.pointsMap.containsKey(name))
                throw new ExceptionHandler("Vertex with given name does not exist !!");
            
            //remove vertex from point map
            g.pointsMap.remove(name);
            //remove all edges going from "Name"
            g.edgeCount-=g.graph.get(name).size();
            g.graph.remove(name);
            g.vertexCount--;
            
            for (Map.Entry<String, SortedMap<String, Integer>> outerEntry : g.graph.entrySet()) 
            {

                String from = outerEntry.getKey();
                //remove all vertices going to "Name"
                if(g.graph.containsKey(from) && g.graph.get(from).containsKey(name));
                {
                    g.edgeCount--;
                    g.graph.get(from).remove(name);
                }

            }
            JOptionPane.showMessageDialog(null,"Vertex : "+name+" removed");
            
            System.out.println("New points map is -");
            g.printPointsMap();
            g.printEdgeMap();
            
        } 
        catch(Exception e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_deleteVerButtonActionPerformed

    private void addEdgeToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEdgeToActionPerformed

    private void addEdgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeButtonActionPerformed
        // TODO add your handling code here:
        String from,to;
        int wt;
        try 
        {
            if(addEdgeFrom.getText().isEmpty() || addEdgeTo.getText().isEmpty() || addEdgeWt.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            from=addEdgeFrom.getText().trim();
            to=addEdgeTo.getText().trim();
            wt=Integer.parseInt(addEdgeWt.getText().trim());
           
            if(!g.pointsMap.containsKey(from))
                throw new ExceptionHandler("Given from vertex does not exist !!");
            
            if(!g.pointsMap.containsKey(to))
                throw new ExceptionHandler("Given to  vertex does not exist !!");
            
            
            if(g.graph.get(from)!=null && g.graph.get(from).containsKey(to))
                throw new ExceptionHandler("An edge already exists between given vertices !!");
            
            g.addEdge(from,to,wt);
            
            JOptionPane.showMessageDialog(null,"Edge added successfully !! ");
            System.out.println("New Edge map is -");
            g.printEdgeMap();
        } 
        catch (Exception e) 
        {
            if(e instanceof NumberFormatException)
                JOptionPane.showMessageDialog(null,"The Weight must be Integer");
            else 
                JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_addEdgeButtonActionPerformed

    private void deleteEdgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEdgeButtonActionPerformed
        // TODO add your handling code here:
        String from,to;
        try 
        {
            if(deleteEdgeFrom.getText().isEmpty() || deleteEdgeTo.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            from=deleteEdgeFrom.getText().trim();
            to=deleteEdgeTo.getText().trim();
           
            if(!g.pointsMap.containsKey(from))
                throw new ExceptionHandler("Given from vertex does not exist !!");
          
            if(!g.pointsMap.containsKey(to))
                throw new ExceptionHandler("Given to  vertex does not exist !!");
                   
            if(g.graph.get(from)==null || !g.graph.get(from).containsKey(to))
                throw new ExceptionHandler("No edge exists between given vertices !!");
            
            g.graph.get(from).remove(to);
            
            JOptionPane.showMessageDialog(null,"Edge deleted successfully !! ");
            System.out.println("New Edge map is -");
            g.printEdgeMap();
            g.edgeCount--;
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_deleteEdgeButtonActionPerformed

    private void modifyEdgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyEdgeButtonActionPerformed
        // TODO add your handling code here:
        String from,to;
        int wt;
        try 
        {
            if(modifyEdgeFrom.getText().isEmpty() || modifyEdgeTo.getText().isEmpty() || modifyEdgeWt.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            from=modifyEdgeFrom.getText().trim();
            to=modifyEdgeTo.getText().trim();
            wt=Integer.parseInt(modifyEdgeWt.getText().trim());
           
            if(!g.pointsMap.containsKey(from))
                throw new ExceptionHandler("Given from vertex does not exist !!");
            
            if(!g.pointsMap.containsKey(to))
                throw new ExceptionHandler("Given to  vertex does not exist !!");
            
            
            if(g.graph.get(from)==null || !g.graph.get(from).containsKey(to))
                throw new ExceptionHandler("No edge exists between given vertices !!");
            
            g.graph.get(from).put(to,wt);
            
            JOptionPane.showMessageDialog(null,"Edge modified successfully !! ");
            System.out.println("New Edge map is -");
            g.printEdgeMap();
        } 
        catch (Exception e) 
        {
            if(e instanceof NumberFormatException)
                JOptionPane.showMessageDialog(null,"The Weight must be Integer");
            else 
                JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_modifyEdgeButtonActionPerformed

    private void addEdgeFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEdgeFromActionPerformed

    private void addEdgeWtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdgeWtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEdgeWtActionPerformed

    private void searchVerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVerButtonActionPerformed
        // TODO add your handling code here:
         String name;
        try 
        {
            if(searchVerName.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            name=searchVerName.getText().trim();
        
            if(!g.pointsMap.containsKey(name))
                throw new ExceptionHandler("Vertex with given name does not exist !!");
            
            int x=g.pointsMap.get(name).get(0);
            int y=g.pointsMap.get(name).get(1);
            
            JOptionPane.showMessageDialog(null, name + " : " + "[ " + x + ", "+ y + " ]");
            System.out.println("New points map is -");
            g.printPointsMap();
        } 
        catch(Exception e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_searchVerButtonActionPerformed

    private void searchEdgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEdgeButtonActionPerformed
        // TODO add your handling code here:
        String from,to;
        try 
        {
            if(searchEdgeFrom.getText().isEmpty() || searchEdgeTo.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            from=searchEdgeFrom.getText().trim();
            to=searchEdgeTo.getText().trim();
           
            if(!g.pointsMap.containsKey(from))
                throw new ExceptionHandler("Given from vertex does not exist !!");
          
            if(!g.pointsMap.containsKey(to))
                throw new ExceptionHandler("Given to  vertex does not exist !!");
                   
            if(g.graph.get(from)==null || !g.graph.get(from).containsKey(to))
                throw new ExceptionHandler("No edge exists between given vertices !!");
            
            int wt=g.graph.get(from).get(to);
            
            JOptionPane.showMessageDialog(null,"Found edge "+from + " => "+to +" "+wt);
            System.out.println("New Edge map is -");
            g.printEdgeMap();
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_searchEdgeButtonActionPerformed

    private void djikSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djikSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_djikSourceActionPerformed

    private void djikDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djikDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_djikDestActionPerformed

    private void djikFindPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djikFindPathActionPerformed
        // TODO add your handling code here:
        String src,dest;
        try 
        {
            if(djikSource.getText().isEmpty() || djikDest.getText().isEmpty())
                throw new ExceptionHandler("Please enter all fields !!");
          
            src=djikSource.getText().trim();
            dest=djikDest.getText().trim();
           
            if(!g.pointsMap.containsKey(src))
                throw new ExceptionHandler("Given source vertex does not exist !!");
          
            if(!g.pointsMap.containsKey(dest))
                throw new ExceptionHandler("Given destination vertex does not exist !!");
                   
            String pathString=g.djik(src,dest);
            
            djikPath.setText(pathString);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_djikFindPathActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
         // TODO add your handling code here:
        try 
        {
            if(fileName.getText().isEmpty())
                throw new ExceptionHandler("Please enter file name !!");
            
            File file= new File(fileName.getText().trim());
            Scanner scan=new Scanner(file);
            
            int v=scan.nextInt();
            scan.nextLine();
            while(v-- > 0)
            {
                String inp[]=scan.nextLine().split(" ");
                String name=inp[0];
                int x=Integer.parseInt(inp[1]);
                int y=Integer.parseInt(inp[2]);

                g.addVertex(name, x, y);
            }
            g.printPointsMap();
            int e=scan.nextInt();
            scan.nextLine();
            while(e-- > 0)
            {
                String inp[]=scan.nextLine().split(" ");
                String from=inp[0];
                String to=inp[1];
                int wt=Integer.parseInt(inp[2]);
                g.addEdge(from, to, wt);
            }
            
            if(scan.hasNextLine())
            {
                throw new ExceptionHandler("Invalid input");
            }
            
            g.printEdgeMap();
            
            JOptionPane.showMessageDialog(null,"Import successfull !!");
            
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Invalid input");
        }
        
    }//GEN-LAST:event_importButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
        try 
        {
            
            File f=new File("output.txt");
            f.createNewFile();
            
            
            FileWriter file=new FileWriter("output.txt");
            int v=g.pointsMap.size();
            file.write(""+v+"\n");
            
            for(Map.Entry<String,List<Integer>> entry : g.pointsMap.entrySet())
            {
                String name=entry.getKey();
                int x=entry.getValue().get(0);
                int y=entry.getValue().get(1);
                
                file.write(name + " " + x + " " + y + "\n");
            }
            
            int e=0;
            for (Map.Entry<String, SortedMap<String, Integer>> outerEntry : g.graph.entrySet()) 
            {

                SortedMap<String, Integer> innerGraph = outerEntry.getValue();
           
                for (Map.Entry<String, Integer> innerEntry : innerGraph.entrySet()) 
                {
                    e++;
                }

            }
            file.write(""+e+"\n");
            
            for (Map.Entry<String, SortedMap<String, Integer>> outerEntry : g.graph.entrySet()) 
            {

                String from = outerEntry.getKey();
                SortedMap<String, Integer> innerGraph = outerEntry.getValue();
           
                for (Map.Entry<String, Integer> innerEntry : innerGraph.entrySet()) 
                {
                    String to = innerEntry.getKey();
                    int wt = innerEntry.getValue();
                    
                    file.write(from + " " + to + " " + wt + "\n");
                }

            }
            JOptionPane.showMessageDialog(null,"Export Successfull to output.txt !!");
            file.close();
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_exportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEdgeButton;
    private javax.swing.JTextField addEdgeFrom;
    private javax.swing.JTextField addEdgeTo;
    private javax.swing.JTextField addEdgeWt;
    private javax.swing.JButton addVerButton;
    private javax.swing.JTextField addVerName;
    private javax.swing.JTextField addVerX;
    private javax.swing.JTextField addVerY;
    private javax.swing.JButton deleteEdgeButton;
    private javax.swing.JTextField deleteEdgeFrom;
    private javax.swing.JTextField deleteEdgeTo;
    private javax.swing.JButton deleteVerButton;
    private javax.swing.JTextField deleteVerName;
    private javax.swing.JTextField djikDest;
    private javax.swing.JButton djikFindPath;
    private javax.swing.JTextArea djikPath;
    private javax.swing.JTextField djikSource;
    private javax.swing.JButton exportButton;
    private javax.swing.JTextField fileName;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modifyEdgeButton;
    private javax.swing.JTextField modifyEdgeFrom;
    private javax.swing.JTextField modifyEdgeTo;
    private javax.swing.JTextField modifyEdgeWt;
    private javax.swing.JButton modifyVerButton;
    private javax.swing.JTextField modifyVerName;
    private javax.swing.JTextField modifyVerX;
    private javax.swing.JTextField modifyVerY;
    private javax.swing.JButton searchEdgeButton;
    private javax.swing.JTextField searchEdgeFrom;
    private javax.swing.JTextField searchEdgeTo;
    private javax.swing.JButton searchVerButton;
    private javax.swing.JTextField searchVerName;
    // End of variables declaration//GEN-END:variables
}
